version: '3'
services:
  front:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app/
    # command: sh -c 'cd mycalc && yarn start'
    ports:
      - '3000:3001'
    tty: true
